import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import {ViewGridIcon, MicrophoneIcon} from '@heroicons/react/solid'
import {SearchCircleIcon} from '@heroicons/react/outline'
import Footer from '../components/Footer'
import { useRef } from 'react'
import {useRouter} from 'next/router'
export default function Home() {
const searchInputRef = useRef(null)
const router = useRouter()
const search =  (e) => {
e.preventDefault()
const term = searchInputRef.current.value;

if (term) {
  router.push(`/search?term=${term}`)

}


}

  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        <div className='flex space-x-4 items-center'> 
          <p className='link'>About</p>
          <p className='link'>Store</p>

        </div>
        <div className='flex space-x-4 items-center'> 
        <p className='link'>Gmail</p>
          <p className='link'
          >Images</p>
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-300 cursor-pointer' />
        <Avatar url='https://pbs.twimg.com/profile_images/1357370920197885953/H8l90Jup_400x400.jpg' />

        </div>
     </header>
     <form className="flex flex-col items-center mt-44 flex-grow">
      <Image 
      width={300}
      height={100}
      src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
      />
      <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl md:max-w-2xl'>
        <SearchCircleIcon className='h-5 mr-3 text-gray-500' />
        <input ref={searchInputRef} type='text' className='focus:outline-none flex-grow' />
        <MicrophoneIcon className='h-5 '/>
      </div>
     </form>
     <div className='flex flex-col w-100 space-y-2 align-center justify-center mt-0 sm:space-y-0 sm:flex-row sm:space-x-4'>
       <button onClick={search} className='btn'>Google Search</button>
       <button onClick={search} className='btn'>I'm feeling lucky</button>
     </div>
     <Footer />
    </div> 
  )
}
